
version: 1
update_configs:
  - package_manager: java:gradle
    directory: /
    update_schedule: daily
    default_reviewers:
    - danirod
    default_assignees:
    - danirod
    default_labels:
    - dependencies
    commit_message:
      prefix: "chore"
      include_scope: true
